# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/natep/miniconda3/bin/cmake

# The command to remove a file.
RM = /home/natep/miniconda3/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/natep/projects/trio-coal/coaldecoder-python

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/natep/projects/trio-coal/coaldecoder-python

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/home/natep/miniconda3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/natep/miniconda3/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\" \"dev\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/home/natep/miniconda3/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/home/natep/miniconda3/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/home/natep/miniconda3/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/home/natep/miniconda3/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/home/natep/miniconda3/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/home/natep/miniconda3/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/natep/projects/trio-coal/coaldecoder-python/CMakeFiles /home/natep/projects/trio-coal/coaldecoder-python//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/natep/projects/trio-coal/coaldecoder-python/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named coaldecoder

# Build rule for target.
coaldecoder: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 coaldecoder
.PHONY : coaldecoder

# fast build rule for target.
coaldecoder/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coaldecoder.dir/build.make CMakeFiles/coaldecoder.dir/build
.PHONY : coaldecoder/fast

#=============================================================================
# Target rules for targets named armadillo

# Build rule for target.
armadillo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 armadillo
.PHONY : armadillo

# fast build rule for target.
armadillo/fast:
	$(MAKE) $(MAKESILENT) -f extern/armadillo-code/CMakeFiles/armadillo.dir/build.make extern/armadillo-code/CMakeFiles/armadillo.dir/build
.PHONY : armadillo/fast

#=============================================================================
# Target rules for targets named smoke_test

# Build rule for target.
smoke_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 smoke_test
.PHONY : smoke_test

# fast build rule for target.
smoke_test/fast:
	$(MAKE) $(MAKESILENT) -f extern/armadillo-code/tests1/CMakeFiles/smoke_test.dir/build.make extern/armadillo-code/tests1/CMakeFiles/smoke_test.dir/build
.PHONY : smoke_test/fast

src/coalescent_model.o: src/coalescent_model.cpp.o
.PHONY : src/coalescent_model.o

# target to build an object file
src/coalescent_model.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coaldecoder.dir/build.make CMakeFiles/coaldecoder.dir/src/coalescent_model.cpp.o
.PHONY : src/coalescent_model.cpp.o

src/coalescent_model.i: src/coalescent_model.cpp.i
.PHONY : src/coalescent_model.i

# target to preprocess a source file
src/coalescent_model.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coaldecoder.dir/build.make CMakeFiles/coaldecoder.dir/src/coalescent_model.cpp.i
.PHONY : src/coalescent_model.cpp.i

src/coalescent_model.s: src/coalescent_model.cpp.s
.PHONY : src/coalescent_model.s

# target to generate assembly for a file
src/coalescent_model.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coaldecoder.dir/build.make CMakeFiles/coaldecoder.dir/src/coalescent_model.cpp.s
.PHONY : src/coalescent_model.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... armadillo"
	@echo "... coaldecoder"
	@echo "... smoke_test"
	@echo "... src/coalescent_model.o"
	@echo "... src/coalescent_model.i"
	@echo "... src/coalescent_model.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

